sudo: required
services:
  - docker

before_install:
  - docker build -t milescolonia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true milescolonia/react-test npm test

after_success:
  - docker build -t milescolonia/multi-client ./client
  - docker build -t milescolonia/multi-nginx ./nginx
  - docker build -t milescolonia/multi-server ./server
  - docker build -t milescolonia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push milescolonia/multi-client
  - docker push milescolonia/multi-nginx
  - docker push milescolonia/multi-server
  - docker push milescolonia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-736911965565
  bucket_path: docker-multi
  on:
    branch: ci
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
